name: Sonar Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # ✅ Added manual trigger

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for accurate analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Ant dependencies
        uses: actions/cache@v4
        with:
          path: ~/.ant/lib
          key: ${{ runner.os }}-ant-${{ hashFiles('**/build.xml') }}
          restore-keys: ${{ runner.os }}-ant

      - name: Install Ivy (for Ant dependencies)
        run: |
          mkdir -p ~/.ant/lib
          curl -L -o ~/.ant/lib/ivy.jar https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.1/ivy-2.5.1.jar

      - name: Build with Ant
        run: |
          ant -f AntSpringMVC/build.xml clean compile

      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for PR decoration
        run: |
          sonar-scanner \
            -Dsonar.projectKey=jeetCl_AntSpringMVC \
            -Dsonar.organization=jeetcl \
            -Dsonar.sources=AntSpringMVC/src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.java.binaries=AntSpringMVC/build \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
