name: Ant Spring MVC SonarCloud Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install JDK 11 (SonarCloud requires at least Java 11 for scanner)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Ant
      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      # Build the project using Ant
      - name: Build with Ant
        run: ant -buildfile AntSpringMVC/build.xml

      # Install Sonar Scanner CLI
      - name: Install Sonar Scanner
        run: |
          mkdir -p $HOME/.sonar
          curl -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          echo "$HOME/.sonar/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      # Run SonarCloud Scan
      - name: SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=jenkins-testing-antspringmvc \
            -Dsonar.organization=jeetcl \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=AntSpringMVC/src \
            -Dsonar.tests=AntSpringMVC/src/com/mkyong/test \
            -Dsonar.java.binaries=AntSpringMVC/war/WEB-INF/classes \
            -Dsonar.java.libraries=AntSpringMVC/lib/*.jar \
            -Dsonar.junit.reportPaths=AntSpringMVC/report/TEST-*.xml \
            -Dsonar.coverage.jacoco.xmlReportPaths=AntSpringMVC/target/jacoco.xml \
            -Dsonar.sourceEncoding=UTF-8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
