name: SonarQube Scan

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    name: Build and analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarQube to get full history

      - name: Set up JDK 17
        uses: actions/setup-java@v4
